name: chitchat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.1.6
  image_picker: ^1.0.7
  get: ^4.6.6
  sqflite: ^2.3.2
  get_it: ^7.6.7
  injectable: ^2.3.2
  font_awesome_flutter: ^10.7.0
  intl: ^0.18.1
  grouped_list: ^5.1.2
  internet_connection_checker_plus: ^2.2.0
  shared_preferences: ^2.2.2
  video_thumbnail: ^0.5.3
  video_player: ^2.8.2
  substring_highlight: ^1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8

flutter:

  uses-material-design: true
